### ISSUE TITLE
Add support for Median absolute deviation

### ISSUE THREAD

**Issue by boristane** [boristane/stat-methods.js#4]
Add support for median absolute deviation, as defined [here](https://en.wikipedia.org/wiki/Median_absolute_deviation).

```js
mad([1, 1, 2, 2, 4, 6, 9]); // -> 1
```

**Update README.md** under _Measures of spread_ and the table of contents.

**Comment by thomasfoster** [comment]
Created PR for this issue

**Comment by boristane** [comment]
Fixed in #77163d0b3f4f1f3c780f5c0281957c8348c31c2d
